name: update-ionq
on:
  schedule:
    - cron: "0 * * * 1-5" # Spustí se každou celou hodinu od pondělí do pátku
  workflow_dispatch: # Aby sis to mohl kdykoliv pustit ručně

jobs:
  update-ionq:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Instalovat jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Stahnout cenu IONQ
      run: |
        # Stažení dat s podporou Pre/Post marketu
        JSON_DATA=$(curl -s "https://query1.finance.yahoo.com/v8/finance/chart/IONQ?includePrePost=true")
        
        # Logika pro výběr nejčerstvější ceny
        POST=$(echo "$JSON_DATA" | jq '.chart.result[0].meta.postMarketPrice // empty')
        PRE=$(echo "$JSON_DATA" | jq '.chart.result[0].meta.preMarketPrice // empty')
        REG=$(echo "$JSON_DATA" | jq '.chart.result[0].meta.regularMarketPrice // empty')
        
        FINAL_PRICE="0.00"
        if [ ! -z "$POST" ]; then
          FINAL_PRICE=$POST
        elif [ ! -z "$PRE" ]; then
          FINAL_PRICE=$PRE
        elif [ ! -z "$REG" ]; then
          FINAL_PRICE=$REG
        fi
        
        IONQ_PRICE=$(printf "%.2f" $FINAL_PRICE)
        echo "{\"cena\": $IONQ_PRICE}" > ionq.json

    - name: Ulozit do ionq.json
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Aktualizace ceny IONQ"
        file_pattern: 'ionq.json'
