name: update-ionq
on:
  schedule:
    - cron: "0 * * * 1-5" # Spustí se každou celou hodinu od pondelí do pátku
  workflow_dispatch: # Aby sis to mohl kdykoliv pustit ručně

jobs:
  update-ionq:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Instalovat jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Stahnout cenu IONQ přes Finnhub
      run: |
        TOKEN="d7t3v4hr01qugn098p9gd7t3v4hr01qugn098pa0"
        
        JSON_DATA=$(curl -s "https://finnhub.io/api/v1/quote?symbol=IONQ&token=$TOKEN")
        
        # Finnhub vrací v klíči 'c' aktuální cenu (včetně pre/after marketu, pokud zrovna běží)
        CENA_AKCIE=$(echo "$JSON_DATA" | jq '.c // empty')
        
        if [ -z "$CENA_AKCIE" ] || [ "$CENA_AKCIE" = "null" ]; then
          CENA_AKCIE="0.00"
        fi
        
        IONQ_PRICE=$(printf "%.2f" $CENA_AKCIE)
        echo "{\"cena\": $IONQ_PRICE}" > ionq.json

    - name: Ulozit do ionq.json
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Aktualizace ceny IONQ pres Finnhub API"
        file_pattern: 'ionq.json'
