name: Aktualizace odpoctu
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-days:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kodu
      uses: actions/checkout@v4

    - name: Spocitat dny
      run: |
        TARGET=$(date -d "2026-07-18" +%s)
        CURRENT=$(date -d "today 00:00:00" +%s)
        DIFF=$(( (TARGET - CURRENT) / 86400 ))
        echo "{\"days\": $DIFF}" > dovca.json

    - name: Ulozit zmeny na GitHub
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add dovca.json
        git commit -m "Automaticky odpocet" || exit 0
        git push
