name: update-days

on:
  schedule:
    - cron: "0 5 * * *"   # každý den v 5:00
  workflow_dispatch:

jobs:
  update-days:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Spocitat dny
        run: |
          python3 scripts/pocitadlo.py

      - name: Nastavit Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Pull latest changes
        run: git pull --rebase

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automaticky dopocet" || echo "No changes to commit"

      - name: Push changes
        run: git push
